php/doc-zh

- reference/misc/functions/pack.xml
close https://github.com/php/doc-zh/issues/36
> Fix typo and Remove PHP 5 for pack

- language/oop5/basic.xml
fix https://github.com/php/doc-zh/issues/51
> Fix missing word

- reference/array/reference.xml
- reference/mbstring/overloading.xml
- reference/strings/functions/chunk-split.xml
- reference/strings/functions/quotemeta.xml
- reference/strings/functions/str-word-count.xml
- reference/strings/functions/strtok.xml
https://github.com/php/doc-en/pull/716
> Remove split() and ereg()

- reference/event/eventconfig/construct.xml
文件的四行注释，我还是没搞懂。第一个是找英文的 version_id 。我真没找到，英文就一个这个:
```xml
<?xml version="1.0" encoding="utf-8"?>
```
第一次提交，都不太懂，如果有的地方不对，麻烦指正
> translate EventConfig::__construct

- reference/pthreads/cond/broadcast.xml
- reference/pthreads/cond/destroy.xml
- reference/pthreads/cond/signal.xml
- reference/pthreads/cond/wait.xml
- reference/pthreads/mutex/destroy.xml
- reference/pthreads/mutex/lock.xml
- reference/pthreads/mutex/trylock.xml
- reference/pthreads/mutex/unlock.xml
- reference/pthreads/pool/resize.xml
- reference/pthreads/pool/shutdown.xml
- reference/pthreads/thread/isjoined.xml
- reference/pthreads/thread/isstarted.xml
- reference/pthreads/thread/join.xml
- reference/pthreads/thread/kill.xml
- reference/pthreads/thread/start.xml
- reference/pthreads/threaded/merge.xml
- reference/pthreads/threaded/notify.xml
- reference/pthreads/threaded/unlock.xml
- reference/pthreads/threaded/wait.xml
- reference/pthreads/worker/isworking.xml
- reference/pthreads/worker/shutdown.xml
https://github.com/php/doc-en/pull/801
> Fix pthreads return values

- reference/event/eventconfig/avoidmethod.xml
- reference/event/eventconfig/construct.xml
- reference/event/eventconfig/requirefeatures.xml
- reference/event/eventconfig/setflags.xml
- reference/event/eventconfig/setmaxdispatchinterval.xml
> translate EventConfig

- language/oop5/variance.xml
https://github.com/php/doc-en/commits/526b0a2fee7ae6abf23b5e4b90c40a275af72e8a/language/oop5/variance.xml
> Added union type link

- reference/array/sorting.xml
https://github.com/php/doc-en/pull/825
> Sorting functions is stable, as of PHP 8.0.0

- language/types/numeric-strings.xml
- translation.xml
Complete the translation of language.types.numeric-strings.
> Complete the translation of language.types.numeric-strings.

- reference/password/functions/password-needs-rehash.xml
https://github.com/php/doc-en/pull/930
> Fix password_needs_rehash method signature

- features/http-auth.xml
https://github.com/php/doc-en/commit/2d1981cc3003cd94f5fb88e0473eed2c5b26efd
> *Only* basic and digest authentication supported

- reference/phar/ini.xml
- reference/phar/setup.xml
并非英语专业人士，只是想着提高自己的英语能力，并希望能够改善 PHP 中文文档。
第一次提交，欢迎提出建议或意见 。
> 翻译 Phar 安装/配置

- language/oop5/inheritance.xml
- language/oop5/properties.xml
- reference/reflection/reflectionproperty/isreadonly.xml
> Add readonly, Fix build error

- language/wrappers/data.xml
- language/wrappers/ftp.xml
- language/wrappers/glob.xml
- language/wrappers/http.xml
- language/wrappers/phar.xml
- language/wrappers/php.xml
> 翻译 wrapper

- language/errors/basics.xml
> Some updates and W/S fixes.

- language/oop5/basic.xml
- language/operators.xml
> 同步language

- security/apache.xml
- security/sessions.xml
- security/variables.xml
> 同步安全部分几个文件的更新

- language/fibers.xml
部分英文专有名词的翻译参考自：language/predefined/fiber.xml
> 翻译 language/fibers

- language/functions.xml
- language/predefined/closure/fromcallable.xml
- language/types/callable.xml
> Fix build error

- chapters/tutorial.xml
We should not encourage use of Notepad for editing PHP files, and those
who use it, should at least know how it works (after all, it's not that
complex).
Sync https://github.com/php/doc-en/commit/6b60bf846bddd05349b7f7ec2d9c1dd0063d3515
> Drop Windows Notepad usage instructions

- language/control-structures/match.xml
- language/predefined/argumentcounterror.xml
- language/predefined/arithmeticerror.xml
- language/predefined/arrayaccess.xml
- language/predefined/assertionerror.xml
- language/predefined/backedenum/from.xml
- language/predefined/backedenum/tryfrom.xml
- language/predefined/error.xml
- language/predefined/error/clone.xml
- language/predefined/errorexception.xml
- language/predefined/exception.xml
- language/predefined/exception/clone.xml
- language/predefined/fibererror.xml
- language/predefined/fibererror/construct.xml
- language/predefined/throwable.xml
- language/predefined/unhandledmatcherror.xml
- language/predefined/valueerror.xml
- language/predefined/weakreference.xml
> 更新 language 章节

- reference/reflection/reflector.xml
https://github.com/php/doc-zh/issues/180
> 更新 Reflector

- reference/apache/functions/apache-get-version.xml
- reference/apache/functions/apache-getenv.xml
- reference/apache/functions/apache-note.xml
- reference/apcu/apcuiterator.xml
- reference/apcu/book.xml
> 更新 apcu 以及 apache 未翻译的内容

- appendices/migration80/new-features.xml
- features/commandline.xml
- language-snippets.ent
- language/oop5/variance.xml
- language/types/declarations.xml
- reference/dir/functions/dir.xml
- reference/filesystem/functions/file.xml
已经同步到最新。并且重新对齐了顺序
> 主要是进行同步，进行翻译的较少
> 同步 language-snippets.ent

- appendices/about.xml
- appendices/comparisons.xml
- appendices/configure/misc.xml
- appendices/configure/servers.xml
- appendices/filters.xml
- appendices/migration70/incompatible/integers.xml
- appendices/migration70/incompatible/strings.xml
- appendices/migration74/new-functions.xml
- install/unix/litespeed.xml
- language/wrappers/rar.xml
- reference/bc/book.xml
- reference/bzip2/functions/bzcompress.xml
- reference/bzip2/functions/bzdecompress.xml
- reference/bzip2/functions/bzflush.xml
- reference/bzip2/functions/bzopen.xml
- reference/bzip2/functions/bzread.xml
- reference/bzip2/functions/bzwrite.xml
- security/cgi-bin.xml
请注意 `install/unix/litespeed.xml` 文件。
英文版地址：https://github.com/php/doc-en/blob/master/install/unix/litespeed.xml#L140 。这段文字的最后一句我不知道如何翻译。麻烦审核时顺便看一下这句话如何处理。
> 更新bzip2 和 bc 以及其他部分

- reference/strings/functions/substr.xml
sync https://github.com/php/doc-en/pull/1219
> Upadte substr

- features/file-upload.xml
there is a missing comma at "upload_tmp_dirpost_max_size"
> add a missing comma

- reference/array/functions/array-keys.xml
sync https://github.com/php/doc-en/pull/1429
> Disambiguate semantics of search_value

- reference/json/jsonserializable.xml
JsonSerializable is an interface
> Fix code block for `JsonSerializable / Interface synopsis`

- reference/exec/functions/escapeshellarg.xml
Add the missing content，according to [English version](https://www.php.net/manual/en/function.escapeshellarg.php)
> Add the execution on Windows

- reference/event/eventconfig/requirefeatures.xml
- reference/event/eventconfig/setflags.xml
- translation.xml
其实内容是最新的，但是我之前不小心把 commit_id 给复制错误了。导致一直提示这俩文件未更新到最新 commit。
另外更新了个人最新邮箱。
> 更新错误的 commit_id

- reference/sockets/functions/socket-addrinfo-connect.xml
- translation.xml
翻译 socket-addrinfo-connect.xml
> Add: translate socket-addrinfo-connect.xml

- chapters/intro.xml
Intro doc page mentions PECL without saying what it is
> Sync chapters/intro

- reference/session/functions/session-module-name.xml
> Sync session_module_name

- reference/sockets/functions/socket-write.xml
> Add: translate socket-write.xml

- reference/sockets/functions/socket-addrinfo-lookup.xml
Translate socket-addrinfo-lookup.xml
> Add: translate socket-addrinfo-lookup.xml

- reference/sockets/functions/socket-set-option.xml
Translate socket-set-option.xml
> Add: translate socket-set-option.xml

- reference/array/functions/array-walk.xml
> Update array-walk.xml  Chinese edition comment

- reference/sockets/functions/socket-get-option.xml
> Add: translate multicast options

- reference/sockets/functions/socket-listen.xml
> Add: translate socket-listen.xml

- reference/sockets/functions/socket-create-pair.xml
Translate socket-create-pair.xml.
> Add: translate socket-create-pair.xml

- reference/sockets/functions/socket-sendto.xml
> Add: translate socket-sendto.xml

- reference/sockets/functions/socket-get-option.xml
> Update: socket-get-option IP_MULTICAST_LOOP

- reference/sockets/functions/socket-send.xml
> Add: translate socket-send.xml

- reference/sockets/functions/socket-getsockname.xml
Translate socket-getsockname.xml
> Add: translate socket-getsockname.xml

- reference/sockets/functions/socket-wsaprotocol-info-export.xml
- reference/sockets/functions/socket-wsaprotocol-info-import.xml
- reference/sockets/functions/socket-wsaprotocol-info-release.xml
翻译 socket_wsaprotocol_info 系列函数
> Add: translate socket_wsaprotocol_info 系列函数

- reference/sockets/functions/socket-select.xml
> Add: translate socket-select.xml

- reference/sockets/functions/socket-recvfrom.xml
> Add: translate socket-recvfrom.xml

- reference/inotify/constants.xml
- reference/inotify/setup.xml
Translate inotify constants.xml and setup.xml
> Add: translate inotify constants.xml and setup.xml

- reference/dio/functions/dio-close.xml
- reference/dio/functions/dio-fcntl.xml
Translate dio-close.xml and dio-fcntl.xml(partial).
> Add: translate dio-close.xml & dio-fcntl.xml

- reference/dio/functions/dio-open.xml
- reference/dio/functions/dio-read.xml
Translate dio-open.xml and dio-read.xml.
> Add: translate dio-open.xml and dio-read.xml

- language/oop5/properties.xml
// invalid property declarations:
正确的属性声明->错误的属性声明
> fix wrong translation

- reference/dio/functions/dio-truncate.xml
- reference/dio/functions/dio-write.xml
Translate dio-truncate & dio-write
> Add: translate dio-truncate & dio-write

- reference/filesystem/functions/fdatasync.xml
- reference/filesystem/functions/fsync.xml
Translate fdatasync and fsync.
> Add: translate fdatasync and fsync

- reference/strings/functions/str-contains.xml
- reference/strings/functions/str-ends-with.xml
- reference/strings/functions/str-starts-with.xml
> Update strings 1

- reference/rrd/book.xml
- reference/rrd/setup.xml
Translate rrd extension intro.
> Add: translate rrd extension intro

- reference/rrd/functions/rrd-create.xml
- reference/rrd/functions/rrd-error.xml
- reference/rrd/functions/rrd-fetch.xml
Translate rrd_creat(), rrd_error(), rrd_fetch().
> Add: translate rrd-create.xml,rrd-error.xml,rrd-fetch.xml

- reference/rrd/functions/rrd-first.xml
- reference/rrd/functions/rrd-graph.xml
- reference/rrd/functions/rrd-info.xml
Translate translate rrd-first.xml,rrd-graph.xml,rrd-info.xml.
> Add: translate rrd-first.xml,rrd-graph.xml,rrd-info.xml

- appendices/migration70/new-features.xml
> fix: php 7.0 new feature typo

- reference/var/functions/is-array.xml
- reference/var/functions/is-float.xml
- reference/var/functions/is-numeric.xml
- reference/var/functions/is-object.xml
- reference/var/functions/is-resource.xml
- reference/var/functions/is-scalar.xml
- reference/var/functions/is-string.xml
> Fix translation of is_* functions

- language/context/zip.xml
- reference/imagick/imagick/getimagealphachannel.xml
- reference/misc/functions/pack.xml
- reference/mysql/functions/mysql-list-tables.xml
- reference/pthreads/pool/collect.xml
- reference/pthreads/worker/unstack.xml
- reference/var/functions/get-debug-type.xml
- Remove very old (4.x) changelog information on a few functions 
- Normalize version strings in changelog entries
- Update get-debug-type.xml
> Sync outdated files

- reference/yaf/yaf_response_abstract/appendbody.xml
> fix typo in Yaf_Response_Abstract::appendBody

- reference/readline/book.xml
- reference/readline/configure.xml
- reference/readline/setup.xml
This reverts commit e9b2a5d88449ecba7f0fd40d49fa2d5fad1fc3c9.
see https://github.com/php/doc-en/commit/51779f7c42f39934403805a42b83cef7126a5fc1
> Revert "Remove GNU Readline in favor of libedit (#912)"

- appendices/filters.xml
- language/predefined/interfaces.xml
- language/predefined/php-incomplete-class.xml
- reference/event/eventconfig/setmaxdispatchinterval.xml
- reference/filesystem/functions/stat.xml
- reference/mcrypt/constants.xml
- reference/oci8/functions/oci-set-prefetch.xml
- reference/sockets/functions/socket-read.xml
- reference/var/functions/unserialize.xml
https://github.com/php/doc-base/pull/181
> Sync skip files

- reference/openssl/functions/openssl-csr-sign.xml
> Sync openssl_csr_sign function

- language-snippets.ent
- language/types.xml
> Fix formatting issue
